export enum PacketKind {
    // Client
    MOVE,
    MOOD,
    SWAP_PETAL,

    WAVE_ROOM_CREATE,
    WAVE_ROOM_JOIN,
    WAVE_ROOM_LEAVE,
    WAVE_ROOM_CHANGE_READY,
    WAVE_ROOM_CHANGE_VISIBLE,

    // Server
    UPDATE,
    SELF_ID,

    SERVER_CLOSED,

    WAVE_ROOM_UPDATE,
    WAVE_ROOM_SELF_ID,
    WAVE_ROOM_JOIN_FAILED,
    WAVE_ROOM_STARTING,
}