export enum ServerBound {
    WAVE_CHANGE_MOVE,
    WAVE_CHANGE_MOOD,
    WAVE_SWAP_PETAL,
    WAVE_CHAT,

    WAVE_ROOM_CREATE,
    
    WAVE_ROOM_JOIN,

    WAVE_ROOM_FIND_PUBLIC,

    WAVE_ROOM_CHANGE_READY,
    WAVE_ROOM_CHANGE_VISIBLE,
    WAVE_ROOM_CHANGE_NAME,

    WAVE_ROOM_LEAVE,
    WAVE_LEAVE,
}

export enum ClientBound {
    WAVE_SELF_ID,
    WAVE_ROOM_SELF_ID,

    WAVE_UPDATE,
    WAVE_ROOM_UPDATE,

    WAVE_ROOM_JOIN_FAILED,

    WAVE_STARTING,

    WAVE_CHAT_RECV,

    CONNECTION_KICKED,
}

export enum ClientboundConnectionKickReason {
    OUTDATED_CLIENT,
    ANTICHEAT_DETECTED,
}